# -*- coding: utf-8 -*-
"""Box Office Data Analytics Project(Dhruv).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VQK39_ddg0G9yzbkA4_RIN-_HdijxxdA

# <center>Box Office Data Analytics</h2>

### Import Libraries
"""

import pandas as pd

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

"""## Task 1: Data Loading and Exploration

# New Section
"""

pd.read_csv("/content/box_office.csv")

print(data.head())
print(data.tail())
print(data.describe())

"""## Task 2: Visualizing the Target Distribution"""

plt.figure(figsize=(10,50))
plt.boxplot(data['revenue'])
plt.xlabel('revenue')
plt.title('visualizing the revenue distribution')
plt.show()



"""## Task 3: Relationship between Film Revenue and Budget"""

plt.figure(figsize=(20,20))
plt.scatter(data['revenue'],data['budget'],color =['blue'])
plt.xlabel('revenue')
plt.ylabel('budget')
plt.title('revenue vs budget') 
plt.show()

"""## Task 4: Distribution of Languages in Film"""

y =data.loc[:,'original_language']

print(y)

language_count=data['original_language'].value_counts()
print(language_count)
plt.figure(figsize=(20,20))
sns.barplot(language_count.index, language_count.values)
plt.title('distributon of laguages')
plt.xlabel('languages', fontsize=20)
plt.ylabel('Number of Occurrences', fontsize=20)
plt.show()



